apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: mlflow-fastapi
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mc
          image: minio/mc
          env:
          - name: MINIO_ROOT_USER
            valueFrom:
                secretKeyRef:
                  name: mlops-secret
                  key: AWS_ACCESS_KEY_ID
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mlops-secret
                  key: AWS_SECRET_ACCESS_KEY
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Configuring alias..." &&
              mc alias set local http://minio-svc:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" &&
              echo "Creating bucket..." &&
              mc mb local/mlflow --ignore-existing &&
              echo "Done."