services:
  mlflow:
    build: ./mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --allowed-hosts localhost:5001,mlflow:5000

  train:
    build: ./train
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_started
    volumes:
      - ./mlruns:/mlruns

  serving:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - MODEL_URI=models:/iris_model/latest
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_started
      train:
        condition: service_completed_successfully
    volumes:
      - ./mlruns:/mlruns

