apiVersion: batch/v1
kind: Job
metadata:
  name: train
  namespace: mlflow-fastapi
  labels:
    app: train
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: train
    spec:
      restartPolicy: Never
      containers:
        - name: train
          image: mlflow-platform/train
          imagePullPolicy: IfNotPresent
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow-service:5200 # maps to service name and service port
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio-svc:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                  secretKeyRef:
                    name: mlops-secret
                    key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                  secretKeyRef:
                    name: mlops-secret
                    key: AWS_SECRET_ACCESS_KEY
