apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow-fastapi

resources:
  - namespace.yaml
  - pvc.yaml
  - minio.yaml
  - minio-init.yaml
  - mlflow.yaml
  - train-job.yaml
  - serving.yaml

secretGenerator:
  - name: mlops-secret
    envs:
      - .env